site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.indexes
  - navigation.path
  - navigation.expand
  - navigation.top
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - content.code.select
  language: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - pymdownx.mark
  - pymdownx.keys
  - attr_list
  - def_list
  - tables
  - admonition

plugins:
  - tags

  - multirepo:
      cleanup: true
      repos:
        - section: Resilient eShop
          import_url: 'https://github.com/Group-50/resilient-eshop.git?branch=main'

site_url: https://group-50.github.io/docs/

# nav:
#   - Home: index.md
#   - Development Guides: 
#     - development-guides/index.md
#     - Docker: development-guides/docker/index.md
#     - Helm: development-guides/helm/index.md
#     - Kubernetes: development-guides/kubernetes/index.md
#     - Terraform: development-guides/terraform/index.md
